"""Ampliar modelo Ingreso

Revision ID: 32b43a9d6957
Revises: fe61c7ae82d4
Create Date: 2025-05-18 00:37:59.185210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b43a9d6957'
down_revision = 'fe61c7ae82d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('modelo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('unidad', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stock_minimo', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('stock_minimo')
        batch_op.drop_column('stock')
        batch_op.drop_column('total')
        batch_op.drop_column('precio')
        batch_op.drop_column('unidad')
        batch_op.drop_column('color')
        batch_op.drop_column('modelo')
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
