"""Agregar id_usuario en ingresos y salidas

Revision ID: 4ffd5a943779
Revises: 749244c6a828
Create Date: 2025-05-06 05:29:29.680006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffd5a943779'
down_revision = '749244c6a828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])

    with op.batch_alter_table('salidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salidas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
