"""Reemplazar id_tipo por tipo_producto en ingresos

Revision ID: ae5a10c10dbe
Revises: 32b43a9d6957
Create Date: 2025-05-18 01:26:54.853703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5a10c10dbe'
down_revision = '32b43a9d6957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_producto', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('ingresos_id_tipo_fkey', type_='foreignkey')
        batch_op.drop_column('id_tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_tipo', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('ingresos_id_tipo_fkey', 'tipos_productos', ['id_tipo'], ['id_tipo'])
        batch_op.drop_column('tipo_producto')

    # ### end Alembic commands ###
