"""empty message

Revision ID: fe61c7ae82d4
Revises: 4ffd5a943779
Create Date: 2025-05-07 11:12:21.423388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe61c7ae82d4'
down_revision = '4ffd5a943779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalles_salida',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_salida', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_salida'], ['salidas.id_salida'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_salida')
    # ### end Alembic commands ###
